default:
  dora_dir: path/to/your_dir
  partitions:
    global: debug
    team: debug
  reference_dir: path/to/your_dir
darwin:  # if we detect we are on a Mac, then most likely we are doing unit testing etc.
  dora_dir: path/to/your_dir
  partitions:
    global: debug
    team: debug
  reference_dir: path/to/your_dir
