# @package __global__

# No conditioning

classifier_free_guidance:
  training_dropout: 0
  inference_coef: 1

attribute_dropout:
  video: {}
  wav: {}

fuser:
  sum: []
  prepend: []
  cross: []
  input_interpolate: []

conditioners: null
