# @package __global__

datasource:
  max_channels: 2
  max_sample_rate: 32000

  evaluate: C:\Users\babingbaboom\Desktop\组会汇报材料\20250918\GVMGen\dataset\eval
  generate: C:\Users\babingbaboom\Desktop\组会汇报材料\20250918\GVMGen\dataset\eval
  train: C:\Users\babingbaboom\Desktop\组会汇报材料\20250918\GVMGen\dataset\train
  valid: C:\Users\babingbaboom\Desktop\组会汇报材料\20250918\GVMGen\dataset\eval
